2.42. Разметка всех страниц
htmlacademy-htmlcss/2158229-device-35 pull request #2
Opened 2022-09-29 12:51 UTC by NADVooDoo

Выполнил домашнее задание [2.42. Разметка всех страниц](https://up.htmlacademy.ru/profession/frontender/15/htmlcss/35/tasks/5)

2022-09-29 14:13 UTC, mkolotovich requested changes
исправь комментарии

2022-09-29 14:13 UTC, mkolotovich commented on catalog.html
> +            <input type="text">
добавь атрибут placeholder c текстом подсказкой - Поиск по сайту

2022-09-29 14:13 UTC, mkolotovich commented on catalog.html
> +          <form>
эта форма не рабочая. Для того чтобы она заработала необходимо добавить атрибуты action и method

2022-09-29 14:13 UTC, mkolotovich commented on catalog.html
> +          <a class="main_header_controls_link" href="#">Корзина</a>
не размечен элемент с цифрой - 2

2022-09-29 14:13 UTC, mkolotovich commented on catalog.html
> +          <li class="main_header_navigation_item">
список из одного элемента - это по-моему избыточно

2022-09-29 14:13 UTC, mkolotovich commented on index.html
> +          <form>
эта форма не рабочая. Для того чтобы она заработала необходимо добавить атрибуты action и method

2022-09-29 14:13 UTC, mkolotovich commented on index.html
> +            <input type="text">
добавь атрибут placeholder c текстом подсказкой - Поиск по сайту

2022-09-29 14:13 UTC, mkolotovich commented on index.html
> +          <a class="main_header_controls_link" href="#">Корзина</a>
не размечен элемент с цифрой - 2

2022-09-29 14:13 UTC, mkolotovich commented on index.html
> +          <li class="main_header_navigation_item">
список из одного элемента - это по-моему избыточно

2022-09-29 14:13 UTC, mkolotovich commented on index.html
> +          <img class="slider_image" src="#" alt="Товары" >
перенесите этот элемент после кнопки - Предыдущий товар, чтобы порядок элементов был как на макете

2022-09-29 14:13 UTC, mkolotovich commented on index.html
> +          <span class="slider_slogan">Порхает как бабочка, жалит как пчела!</span>
это лучше заменить на b или strong

2022-09-29 14:13 UTC, mkolotovich commented on index.html
> +          <span class="slider_slogan">Порхает как бабочка, жалит как пчела!</span>
Пропустили параграф с описанием товара

2022-09-29 14:13 UTC, mkolotovich commented on index.html
> +        <a class="delivery_form_link" href="#">
я думаю, что это не интерактивный элемент, а просто див

2022-09-29 14:13 UTC, mkolotovich commented on index.html
> +              <span class="delivery_form_info">i</span>
а вот это похоже на интерактивный элемент

2022-09-29 14:13 UTC, mkolotovich commented on index.html
> +      <section class="delivery_form">
эта обертка лишняя. Вот критерий - https://up.htmlacademy.ru/htmlcss/35/criteries#HTML-06

2022-09-29 14:13 UTC, mkolotovich commented on index.html
> +          <a class="contacts_phone" href="tel:+78005558628">+7 800 555-86-28</a>
в макете другой номер

2022-09-29 14:13 UTC, mkolotovich commented on index.html
> +          <a class="contacts_phone" href="tel:+78005558628">+7 800 555-86-28</a>
в макете другой телефон

2022-09-29 14:13 UTC, mkolotovich commented on index.html
> +            <button class="main_header_navigation_button">Каталог товаров</button>
это ссылка, а не кнопка

2022-09-29 14:13 UTC, mkolotovich commented on catalog.html
> +          </button>
тут должен быть - Коля Петухов и кнопка - Выйти)

2022-09-29 14:13 UTC, mkolotovich commented on catalog.html
> +          <!-- Фильтры -->
пропустил - текст Фильтр и Стоимость с ползунком

2022-09-29 14:13 UTC, mkolotovich commented on catalog.html
> +        <!-- Сортировка по возрастанию и убыванию-->
Пропустил текст - сортировка:

2022-09-29 14:13 UTC, mkolotovich commented on catalog.html
> +          <option value="popular">Популярное</option>
в макете - Популярные

2022-09-29 14:13 UTC, mkolotovich commented on catalog.html
> +        </a>
это лучше обернуть в один элемент, например див

2022-09-29 14:13 UTC, mkolotovich commented on catalog.html
> +            </a>
здесь и далее в других карточках, зачем тут две ссылки? Причем ведущие в разные места. Это должна быть одна ссылка на один товар.

2022-09-29 14:13 UTC, mkolotovich commented on catalog.html
> +              <b class="product_card_price">500 ₽</b>
здесь и далее в других карточках, лучше использовать спан, тут ведь не жирный текст в макете

2022-09-29 14:13 UTC, mkolotovich commented on catalog.html
> +            <a class="pagination_link" href="#">4</a>
такого в макете нет, есть - ...

2022-09-29 14:13 UTC, mkolotovich commented on catalog.html
> +            <a class="pagination_link" href="#">5</a>
такого в макете нет, есть - 15

2022-09-29 14:13 UTC, mkolotovich commented on catalog.html
> +          <a class="contacts_phone" href="tel:+78005558628">+7 800 555-86-28</a>
в макете другой телефон

2022-09-29 14:51 UTC, mkolotovich requested changes
Ты исправил не все комментарии с прошлой проверки. Плюс добавились новые

2022-09-29 14:51 UTC, mkolotovich commented on .editorconfig
> +indent_size = 2
этот файл в репозитории не нужен. Добавьте его в .gitignore

2022-09-29 14:51 UTC, mkolotovich commented on catalog.html
>                <button class="main_header_controls_button" type="button">
чтобы форма отправлялась тип должен быть submit

2022-09-29 14:51 UTC, mkolotovich commented on index.html
>                <button class="main_header_controls_button" type="button">
чтобы форма отправлялась тип должен быть submit

2022-09-29 15:38 UTC, NADVooDoo commented on catalog.html
> +          <!-- Фильтры -->
В скринкасте сказали чтобы этот блок пропустили, потому что в разделе 8 кажется там кто-то научит с нуля этот блок верстать.

2022-10-03 18:00 UTC, pavel-nyukalo requested changes

2022-10-03 18:00 UTC, pavel-niukalo commented on .editorconfig
> +indent_size = 4
Тут менять кол-во пробелов не нужно, поскольку по [критерию](https://up.htmlacademy.ru/htmlcss/35/criteries#PROJ-01) код должен соответствовать правилам кодгайда Академии, а там стоит 2 пробела 

![image](https://user-images.githubusercontent.com/52506235/193642034-75df538b-5ebd-4453-94df-ff7c99fc64d9.png)

2022-10-03 18:00 UTC, pavel-niukalo commented on catalog.html
> +          <form class="main_header_find"  action="https://echo.htmlacademy.ru/" method="submit">
`submit` должен быть указан у кнопки в атрибуте `type="submit"`, иначе это ошибка валидации

![image](https://user-images.githubusercontent.com/52506235/193643479-6858f682-3b83-459c-806b-258d61dcbc2d.png)

2022-10-03 18:00 UTC, pavel-niukalo commented on catalog.html
> +          </form>
Тут нужно поправить кол-во пробелов. Двумя пробелами отделяются вложенный элементы - `button` у нас не вложен в `input`, соответственно тут должно быть так
```html
<form>
  <input>
  <button>
    Найти
  </button>
</form  
```

То есть не должно быть отступов в 4 пробела, как сейчас у `</button>` и `</form>`

2022-10-03 18:00 UTC, pavel-niukalo commented on catalog.html
> +          </fieldset>
Так же нужно поправить отступы:
```html
    </li>
  </ul>
</fieldset>
```

2022-10-03 18:00 UTC, pavel-niukalo commented on catalog.html
> +          <h3 class="visually_hidden">Фильтр:</h2>
Открылся `h3`, закрылся `h2`

2022-10-03 18:00 UTC, pavel-niukalo commented on catalog.html
> +            <input type="range" min="0" max="9000" steps="590" value="590" steps="500" value="500">
Два раза указаны `steps` и `value` + у `input` нет атрибута `steps`

![image](https://user-images.githubusercontent.com/52506235/193643814-e10a0849-5f1a-446f-9080-2f02a5be622d.png)

2022-10-03 18:00 UTC, pavel-niukalo commented on catalog.html
> +        <a class="main_footer_copy" href="#">
Не забудь добавить необходимые ссылки - требование ТЗ

![image](https://user-images.githubusercontent.com/52506235/193644193-f865ed5f-89d7-4c1d-9cd1-74cf432109db.png)

2022-10-03 18:00 UTC, pavel-niukalo commented on index.html
> +              <button class="main_header_controls_button" type="button">
Аналогично каталогу - `submit` должен быть у `button`

2022-10-03 18:00 UTC, pavel-niukalo commented on index.html
> +          </form>
И так же про отступы

2022-10-03 18:00 UTC, pavel-niukalo commented on index.html
> +        </div>
Не забудь добавить остальные слайды

![image](https://user-images.githubusercontent.com/52506235/193644544-a06b4f6a-1b7c-4f45-8b04-3ad3450af2eb.png)

2022-10-03 18:00 UTC, pavel-niukalo commented on index.html
> +          <p class="delivery_carousel_text">Мы с удовольствием доставим ваш товар прямо к вашему подъезду совершенно бесплатно! Ведь мы неплохо заработаем, поднимая его на ваш этаж.</p>
Так же не забудь добавить контент остальных вкладок

![image](https://user-images.githubusercontent.com/52506235/193645152-648e6ff6-ad87-4fb7-a5d0-59ab9e51e360.png)

2022-10-03 18:00 UTC, pavel-niukalo commented on index.html
> +        </ul>
Если ориентироваться на стайлгайд, то у нас тут один интерактивный элемент (ссылка). Поэтому лучше сделать это все одним элементом, а иконочки и тд уже можно будет через `span` условный сделать

![image](https://user-images.githubusercontent.com/52506235/193645910-4f9f41a9-fe4b-42c6-9e3a-65ba7e28bd1f.png)

2022-10-03 18:00 UTC, pavel-niukalo commented on index.html
> +      </a>
Этот закрывающий тег надо закрыть

![image](https://user-images.githubusercontent.com/52506235/193646400-00db2313-020b-4f7d-ab61-a5f74ca5e9d3.png)

2022-10-03 18:00 UTC, pavel-nyukalo commented on index.html
> +            </button>
Отступы поправить нужно

2022-10-04 08:46 UTC, NADVooDoo commented on catalog.html
> +            <input type="range" min="0" max="9000" steps="590" value="590" steps="500" value="500">
Это поле я для вида засунул. В лайвах сказали его вообще не трогать и будем делать в 8 разделе, кажется. Я все атрибуты уберу тогда...

2022-10-05 15:32 UTC, pavel-nyukalo approved these changes

2022-10-05 15:32 UTC, merged