Микросетки на флексах для всех страниц
htmlacademy-htmlcss/2158229-device-35 pull request #6
Opened 2022-10-27 14:08 UTC by NADVooDoo

Домашнее задание 6.18. Микросетки на флексах для всех страниц

---
:mortar_board: [Микросетки на флексах для всех страниц](https://up.htmlacademy.ru/htmlcss/35/user/2158229/tasks/11)

:boom: https://htmlacademy-htmlcss.github.io/2158229-device-35/6/

2022-10-28 10:53 UTC, pavel-nyukalo requested changes

2022-10-28 10:53 UTC, pavel-nyukalo commented on catalog.html
> +          <li class="main_header_controls_item">
Здесь не нужен этот отступ, нужно вернуть как было

2022-10-28 10:53 UTC, pavel-nyukalo commented on catalog.html
> +
Для единообразия лучше один перенос оставить

2022-10-28 10:53 UTC, pavel-nyukalo commented on catalog.html
> +                </a>
Можно стилизовать без `span`, сразу ссылку

2022-10-28 10:53 UTC, pavel-nyukalo commented on catalog.html
> +                <div class="social_link_circle"></div>
А здесь можно стилизовать сразу ссылку, без добавления лишней обертки

2022-10-28 10:53 UTC, pavel-nyukalo commented on index.html
> +          </li> -->
Закомментированого кода у нас не должно быть, можно добавить доп. класс, который скроет эту кнопку

2022-10-28 10:53 UTC, pavel-nyukalo commented on index.html
> +              <div class="showcase_wrapper">
Здесь аналогично, можно стилизовать сразу ссылку, без добавления лишней обертки

2022-10-28 10:53 UTC, pavel-nyukalo commented on index.html
> +          <div class="line"></div>
Выглядит чисто декоративом, поэтому в разметку тащить не стоит. Можно сделать псевдоэлементом

2022-10-28 10:53 UTC, pavel-nyukalo commented on styles/styles.css
> +  z-index: 1;
Поскольку у нее `border-box`, то левый паддинг съедает ширину. И ссылка по размерам получается 30*50

![image](https://user-images.githubusercontent.com/52506235/198567845-36563ff3-9ee6-469d-9fc0-0ed0b87d19dd.png)

Что немного не соответствует действительности, поскольку картинка у нас 50*50. Паддинг получается служит для отступа от текста, а в таком случае лучше использовать левый марджин (как раз внешний отступ), и тогда и отступ будет, и размеры ссылки 50*50

2022-10-28 10:53 UTC, pavel-nyukalo commented on styles/styles.css
> +margin-bottom: 48px;
Отступы надо добавить для единообразия

2022-10-28 11:25 UTC, NADVooDoo commented on catalog.html
> +                </a>
![pagnt](https://user-images.githubusercontent.com/108404948/198576345-67b422bb-5e39-49fb-ad0f-cff30ebe42c1.png)
Принял! Я просто сделал как в скринкасте показали и на лайве.

2022-10-30 14:45 UTC, pavel-nyukalo commented on catalog.html
> +      <!-- Шапка нижняя с навигацией -->
Второй `li` и `</ul>` тоже нужно подвинуть, сейчас получается, что `</ul>` и `</div>` на одном уровне

2022-10-30 14:45 UTC, pavel-nyukalo commented on catalog.html
> +
Не исправлено, стоит оставить один перенос, не два

2022-10-30 14:45 UTC, pavel-nyukalo commented on catalog.html
> +                </a>
В скринкасте добавлен скрытый `span` с подписью, а у нас уже есть проговариваемый текст "Назад", поэтому предлагаю сразу ссылку стилизовать

2022-10-30 14:49 UTC, pavel-nyukalo requested changes

2022-10-30 14:49 UTC, pavel-nyukalo commented on catalog.html
> +                </a>
[Оставил комментарий](https://github.com/htmlacademy-htmlcss/2158229-device-35/pull/6#discussion_r1008877189), поэтому тут тоже надо будет так сделать

2022-10-31 07:24 UTC, pavel-nyukalo approved these changes

2022-10-31 07:24 UTC, merged