Завершаем вёрстку всех компонентов
htmlacademy-htmlcss/2158229-device-35 pull request #9
Opened 2022-11-13 16:38 UTC by NADVooDoo

д/з 9.18. Завершаем вёрстку всех компонентов

На страницах есть и модальное окно и поповер корзины. Я их подписал в комментариях. **По-умолчанию они скрыты.**

2022-11-14 06:35 UTC, pavel-nyukalo requested changes

2022-11-14 06:35 UTC, pavel-niukalo commented on catalog.html
> +                      <img class="popover_product-card_img" src="/images/catalog/product_1.jpg" alt="Фотография Любительской селфи-палки.">
Слеш в начале `src` надо заменить либо на `./images/...`, либо просто `images/...`, иначе на сервере картинка не подгрузится

2022-11-14 06:35 UTC, pavel-nyukalo commented on catalog.html
> +                      <span class="visually_hidden">Удалить из корзины</span>
Точку в конце описания

2022-11-14 06:35 UTC, pavel-niukalo commented on catalog.html
> +                    <button class="range_toggle toggle_min">
По критерию у `button` должны быть указаны `type`

2022-11-14 06:35 UTC, pavel-niukalo commented on catalog.html
> +                      <div class="product_card_title_wrapper">
1. У этого дива лишние отступы, нужно вернуть как было
2. По макету у нас подсвечивается вся карточка

![image](https://user-images.githubusercontent.com/52506235/201589619-fe5cbc3c-584a-4e98-ab46-f5890c5086ab.png)

Сейчас вот так:
![image](https://user-images.githubusercontent.com/52506235/201589655-ed3fbc8c-add4-4533-9e2b-1579428616d1.png)

2022-11-14 06:35 UTC, pavel-nyukalo commented on index.html
> +                      <span class="visually_hidden">Удалить из корзины</span>
Тут аналогично все

2022-11-14 06:35 UTC, pavel-niukalo commented on index.html
> +        </button>
Так же про `type` и точку в конце

2022-11-14 06:35 UTC, pavel-nyukalo commented on index.html
> +              </span>
С `z-index` надо поработать

![image](https://user-images.githubusercontent.com/52506235/201590744-f183ce6c-8d1c-4441-bb3c-59be46a27b36.png)

2022-11-14 06:35 UTC, pavel-nyukalo commented on styles/styles.css
> +  font-family: "Rubik";
Семейство тоже надо задать

2022-11-14 06:35 UTC, pavel-nyukalo commented on styles/styles.css
> +.quantity_inner .bt_plus svg {
Вложенность больше трех - по критерию запрещено.
Можно сделать `.bt_minus svg, .bt_plus svg {}`

2022-11-14 06:35 UTC, pavel-nyukalo commented on styles/styles.css
> +input::-webkit-inner-spin-button {
Стилизация по тегу - запрещена критерием

2022-11-15 08:54 UTC, NADVooDoo commented on index.html
> +              </span>
Честно говоря, у меня ни в хроме ни в мозилле такого не было. Но я поправил на всякий случай z-index..

2022-11-15 12:15 UTC, pavel-nyukalo approved these changes

2022-11-15 12:15 UTC, merged